eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/users/current
      token-info-uri: http://auth-service/uaa/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
