tracer:
  property: "I AM THE DEVELOPMENT CONFIGURATION"
spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://database:3306/salonapidb-dev
    username: salondbuser
    password: ThePassword
    testWhileIdle: true
    validationQuery: SELECT 1
