spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/salonapi
    username: 'salondbuser'
    password: 'ThePassword'
signing:
  key: "9as6f5das6fyda9e5"
