spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
signing:
  key: "{cipher}22157947cc2e69870b6c65e09ef20410234334256a0a56afefa9ea237dd4c8dc7f5060c7e5e66da2344f33c2564501c5"
server:
  servlet:
    context-path: /uaa
  port: 8901
logging:
  level:
    com.netflix: WARN
    com.springframework.web: WARN
    com.github.willwbowen: DEBUG
