spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    url: "jdbc:mysql://database:3306/salonapidb"
    username: "root"
    password: "root"
signing:
  key: "9as6f5das6fyda9e5"
