spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
    initialization-mode: always
signing:
  key: "{cipher}22157947cc2e69870b6c65e09ef20410234334256a0a56afefa9ea237dd4c8dc7f5060c7e5e66da2344f33c2564501c5"
server:
  servlet:
    context-path: /uaa
  port: ${AUTHSERVICE_PORT}
logging:
  level:
    com.netflix: WARN
    com.springframework.web: WARN
    com.github.willwbowen: DEBUG

seed:
  data:
    username: randomuser
    browser-client: browser
    account-client: account-service
    password: "{cipher}48c3990b39cece97f937ae7aba1dceb9a82027040d6913af62f9cc06cde59f45"
